#!/usr/bin/env bash
#
# Install the dotfiles

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

info () {
	printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
	printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
	echo ''
	exit
}

confirm () {
	# call with a prompt string or use a default
	user " ${1:-Are you sure? [Y/n]}"
	read -e response
	case $response in
		[nN]) 
			false
			;;
		*)
			true
			;;
	esac
}

setup_gitconfig () {
	if ! [ -f git/.gitconfig ]
	then
		info 'setup gitconfig'

		user ' - What is your git author name?'
		read -e git_authorname
		user ' - What is your git author email?'
		read -e git_authoremail

		sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" script/gitconfig.dist > git/.gitconfig

		success 'gitconfig'
	fi
}

install_dependecies () {
	info 'install dependecies'

	# redshift
	sudo add-apt-repository -y ppa:dobey/redshift-daily

	sudo apt update && sudo apt install stow vim tmux git redshift redshift-gtk keepassx
}

link_dotfiles () {
	info 'link dotfiles'

	dir="git"

	# link stow-global-ignore because stow ignore .gitignore by default
	ln -sf "$DOTFILES_ROOT/script/.stow-global-ignore" $HOME

	if confirm "Whish to link all folders? [Y/n]"; then
	  link_all=true
	else
	  link_all=false
	fi

	for dir in *;
	do
		# skip if not a directory or is one of the protected dir
		[[ -d "$dir" ]] && [[ ! "bin functions script system" =~ $dir ]] || continue

		if [[ "$link_all" == false ]]; then
			if confirm "Link $dir? [Y/n]"; then
				stow "$dir"
			fi
		else
			stow "$dir"
		fi

		success "linked $dir"
	done
}

link_home_folders () {
	info 'link home folders'

	if confirm "Whish to link your home folders? [Y/n]"; then
		user "Type the path of your home folder [/media/user/home]"
		read -e home_folder

		# Documents
		rm -rf ~/Documents
		ln -s "$home_folder/Documents" ~/

		# Downloads
		rm -rf ~/Downloads
		ln -s "$home_folder/Downloads" ~/

		# Pictures
		rm -rf ~/Pictures
		ln -s "$home_folder/Pictures" ~/

		# Projetos
		rm -rf ~/Projetos
		ln -s "$home_folder/Projetos" ~/
	fi
}

# setup_gitconfig
# install_dependecies
link_dotfiles
link_home_folders
